version: '3.9'
services:
    db:
        image: postgres:14.4
        restart: always
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DB
        volumes:
            - ./db/docker-entrypoint-initdb.d/creare-tables.sql:/docker-entrypoint-initdb.d/creare-tables.sql
        logging:
            options:
                max-size: 10m
                max-file: 3
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
            interval: 5s
            timeout: 10s
            retries: 5
            start_period: 30s
        networks:
            - back_tier
    app:
        image: python:3.8-slim-buster
        build: ./app
        environment:
            - APP_HOST
            - APP_PORT
        ports:
            - "${APP_PORT}:${APP_PORT}"
        healthcheck:
            test: ["CMD-SHELL", "curl --fail -s http:/${APP_HOST}:${APP_PORT}/ || exit 1"]
            interval: 5s
            timeout: 10s
            retries: 5
            start_period: 30s
        depends_on:
            db:
                condition: service_healthy
        networks:
            - back_tier
volumes:
    db:
        driver: "local"
networks:
    front-tier:
    back_tier: